# Generated by Django 5.2.4 on 2026-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='role',
            field=models.CharField(choices=[('LECTURER', 'Lecturer'), ('MONITOR', 'Monitor'), ('ADMIN', 'Admin')], max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LECTURER', 'Lecturer'), ('MONITOR', 'Monitor'), ('ADMIN', 'Admin')], max_length=16),
        ),
    ]
