# Generated by Django 5.2.4 on 2026-04-01 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_notification_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='monitor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MONITOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='monitor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MONITOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_semesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='YearOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years_of_study', to='api.course')),
                ('monitor', models.ForeignKey(limit_choices_to={'role': 'MONITOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_years_of_study', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years_of_study', to='api.semester')),
            ],
        ),
    ]
