# Generated by Django 5.2.4 on 2026-04-01 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_programme_semester_year_of_study_course_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearofstudy',
            name='monitor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MONITOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_years_of_study', to=settings.AUTH_USER_MODEL),
        ),
    ]
